//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string NRIC { get; set; }
        public string Name { get; set; }
        public System.DateTime Birthday { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public string Gender { get; set; }
        public bool English { get; set; }
        public bool Math { get; set; }
        public bool Science { get; set; }
        public int ID { get; set; }
    }
}
